export const RECEIVE_EXAMS = 'RECEIVE_EXAMS'
export const ADD_EXAM = 'ADD_EXAM'
export const UPDATE_EXAM = 'UPDATE_EXAM'

export const DELETE_EXAM = 'DELETE_EXAM'
export const GET_EXAM = 'GET_EXAM'
export const GET_EXAMS = 'GET_EXAMS'
export const EDIT_EXAM = 'EDIT_EXAM'
export const RECEIVE_QUESTIONS = 'RECEIVE_QUESTIONS'
export const EDIT_QUESTION = 'EDIT_QUESTION'
export const ADD_QUESTION = 'EDIT_QUESTION'
export const DELETE_QUESTION = 'DELETE_QUESTION' 
export const START_LOADING = 'START_LOADING'
export const END_LOADING = 'START_LOADING'
export const RANDOM_QUESTION = 'RANDOM_QUESTION'


